### ISSUE TITLE
Detect if SD card is locked

### ISSUE THREAD

**Issue by carolineclark** [KanoComputing/kano-burners#26] opened 2014-11-18 08:50 UTC
A customer reported:

About the burner, I didn't notice that my SDcard was locked.

Now that I've unlocked it, the image is downloading properly.

Maybe the burner could be improved to detect the lock and give a more descriptive feedback than "an error has occurred".

**Comment by Ealdwulf** [comment] 2015-04-22 17:50
Closing as a duplicate of #12

**Closed by Ealdwulf** 2015-04-22 17:50 UTC
Labels: 1 - ToDo, development, Med Prio
